name: BukkitBackdoor
author: balugaq
description: A Bukkit plugin
main: com.balugaq.bukkitbackdoor.implementation.BukkitBackdoorPlugin
website: https://github.com/balugaq/BukkitBackdoor
version: ${project.version}
api-version: 1.20
